# Generated by Django 4.1.4 on 2022-12-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Не более 50 символов', max_length=50, verbose_name='Название города')),
                ('slug', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
